#!/usr/bin/env python3
import os
import sys
import helpers

from analyzer import Analyzer
from termcolor import colored
def main():
#accepts one and only one command-line argument, the screen name for a user on Twitter,
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets screenname")
    else:
        name = sys.argv[1]

        positives = os.path.join(sys.path[0], "positive-words.txt")
        negatives = os.path.join(sys.path[0], "negative-words.txt")
    #queries Twitter’s API for a user’s most recent 50 tweets
        from helpers import get_user_timeline 
        tweetlist = helpers.get_user_timeline(name,50)

    #analyzes the sentiment of each of those tweets
        # instantiate analyzer
        tw_analyzer = Analyzer(positives, negatives)
        # analyze word
        for tweet in tweetlist:
            score =  tw_analyzer.analyze(tweet)
            if score > 0.0:
                print(colored("{} {}".format(score, tweet), "green"))
            elif score < 0.0:
                print(colored("{} {}".format(score, tweet), "red"))
            else:
                print(colored("{} {}".format(score, tweet), "yellow"))

            
#outputs each tweet’s score and text, colored in green if positive, red if negative, and yellow otherwise.

if __name__ == "__main__":
    main()